name: Nest.js Test

on: [push, pull_request]

jobs:
  nest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd desafio-github
      - run: yarn
      - run: yarn test
